app = "olympics-pwa"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "2s"

[env]
  ENVIRONMENT = "production"
  PYTHONPATH = "/app"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1