[phases.setup]
nixPkgs = ['python311', 'nodejs_20']

[phases.install]
dependsOn = ['setup']
cmds = [
    'cd apps/api && pip install -r requirements.olympics.txt',
    'cd apps/web && npm ci'
]

[phases.build]
dependsOn = ['install']
cmds = ['cd apps/web && npm run build']

[start]
cmd = 'cd apps/api && python -m uvicorn app.main_olympics_only:app --host 0.0.0.0 --port $PORT'