-- Update gameboard stations with the ACTUAL game content
-- First, clear existing stations
DELETE FROM gameboard_stations;

-- Insert the actual game stations with exact stories and challenges
INSERT INTO gameboard_stations (id, name, description, narrative, required_skill, completion_reward_xp, position_x, position_y) VALUES

(1, 'Saddledome Challenge', 'Primary venue for ice hockey and figure skating with ticket bidding war', 'The Olympic Saddledome was the primary venue for ice hockey and figure skating. Located at Stampede Park, the facility was expected to cost $83 million but cost overruns pushed the facility to nearly $100 million. The organizing committee overpromised tickets to insiders and sponsors for seats to the premier Gold Medal Hockey game at the Saddledome. This is the first year that NHL players were allowed to play in the Olympics and Canada is a favourite to win the Gold medal against the dominating Soviet Union team. CHALLENGE: Politically you are pressured to find 2 tickets for Andy Moog, Canada''s goaltender and 3-time Stanley Cup Champion. You get a lead that a major sponsor has tickets to give away but by the time you call they have already engaged Finland''s Chef de Mission in a deal. You enter into a bidding war to get these tickets.', 'Strength', 750, 15, 15),

(2, 'McMahon Stadium', 'Closing ceremony tickets and volunteer scalping situation', 'Closing ceremony tickets were promised to all volunteers but the organizers quickly realized that there was more demand for seats than tickets. Volunteers who had no interest in seeing the closing ceremony found they could scalp their tickets at high prices at various venues around town in the last week of the Games. CHALLENGE: You need some tickets for a VIP guest so you head down to the Olympic Village to try and score some tickets. Will you be successful?', 'Strength', 500, 25, 25),

(3, 'Nakiska Ski Venue Downhill Course', 'Controversial venue with snow machine debate', 'There was a lot of controversy when Nakiska was awarded the contract for all downhill events. For many reasons, it was considered an inferior venue for an Olympic event. Apart from a not-very-technical course, the Nakiska ski area was notorious for having a lack of snow. The venue was banking on having a good snow year but just in case, a fleet of snow guns were brought in from the USA. When FIS inspects the course they think the base is too thin and wants to supplement with machine-made snow but other countries want to let the event go ahead with the subpar natural snow. CHALLENGE: As Chef, you know your athletes are used to racing on machine-made snow and will have an advantage. You put in an appeal the other countries'' request to go ahead with the event on real snow.', 'Climbing', 500, 35, 35),

(4, 'Winsport Ski Jumping', 'Chinook winds threatening to delay the jumping event', 'The Winsport (now known as Canada Olympic Park) facility was built in Calgary to house bobsleigh, luge and the jumping events. The original park was built with 5 jumps ranging from K4-K90 ratings. The Canadian team has been training on these jumps for years. However, the Chinook winds have blown in just as the event is slated to start. There''s a decent chance the winds might be too high for a safe jumping event. The Canadian team is prepped and ready to take the chairlift to the top of the course where the coach is waiting. CHALLENGE: As the Chef de Mission you''re onsite at the venue to decide alongside the jury whether the event should go ahead or not based on the wind readings. You know your team is psychologically prepared to race and you want FIS to let the race go ahead. The other countries, led by a very vocal Austrian contingent are pushing FIS to delay the start.', 'Speed', 750, 45, 45),

(5, 'Canmore Nordic Centre Cross Country', 'Mass start 50km event with broken pole dilemma', 'The cross country coach requires your assistance today to stand on course with a spare pole in case a Canadian breaks one in the mass start event of the 50km event. CHALLENGE: As you''re standing on course, an Italian racer breaks a pole right in front of you. In that moment, you decide to give the Italian team the pole intended for the Canadians.', 'Endurance', 750, 55, 55),

(6, 'Canmore Nordic Centre Biathlon', 'Poor Canadian performance and media attention dilemma', 'The story at the biathlon centre is that the events have been dominated by 3 nations (USSR, East and West Germany). There is zero chance that Canadians will break the top 30 but the Nation always wants to rally around a relay event to cheer on their country. As the Chef de Mission, you know your appearance at the race site will provoke media questions about why Canada has such a dismal record in this sport. CHALLENGE: Staying away will ensure you don''t have to answer difficult questions but the optics are bad if you show no support to the biathletes during these Olympics. You decide to skip the event.', 'Endurance', 500, 65, 65),

(7, 'Olympic Oval Short Track Event', 'Ice surface specifications controversy', 'Built specifically for the Olympics, the speed skating venue was located on the University of Calgary and was named the Olympic Oval. It was the first covered speed skating oval in North America, and offered superior climate control for ideal ice conditions. In the preliminary rounds of the short track event the ISU, speed skating''s international federation observes very fast event times. They are concerned that the ice surface is not built to specifications. CHALLENGE: Knowing that the Canadian team is trained to skate well on this surface, you are arguing for an outcome that will leave the ice as built. An inspection team arrives to take measurements.', 'Speed', 750, 75, 75),

(8, 'Olympic Oval Long Track Event', 'World record ice and scheduling conflicts', 'The covered ice combined with the high altitude in Calgary has led to the ice on the Olympic Oval being dubbed "The Fastest Ice in the World". So far, during the Olympics, 3 world records and 2 Olympic records have fallen. As the Chef de Mission, your presence at the Olympic Oval is in high demand to take interviews every time a record falls. CHALLENGE: You''ve spent too much time at the Olympic Oval and need to support some athletes in the snowboard competition but there''s a good chance Canada will win the 5000m today against the Netherlands. Since the Netherlands have been skating better than expected, you decide to head to snowboarding instead.', 'Endurance', 750, 85, 85),

(9, 'Ski Jumping', 'Eddie the Eagle and Todd Gilman media crisis', 'Lots of attention coming out of the ski jumping venue after the British ski jumper, known as Eddie the Eagle came in last place on the normal hill (K70), failing to hit the 70m mark with two jumps of 61m. Now, in the large hill event, a Canadian, Todd Gilman, is currently sitting behind Eddie the Eagle in last place. Eddie jumped 68.5m and 71m, his personal best and a British record while Todd only managed 69m jump on his first round. CHALLENGE: The press cannot let this story drop since there has already been talk about instituting minimal jump rules to prevent this from happening again in the future. You have to defend the selection criteria for Team Canada to the media.', 'Climbing', 500, 95, 95),

(10, 'Luge', 'East German doping rumors and media interview', 'The East German team sweeps the women''s luge single podium. There is a lot of chatter in the Athlete Village that there is doping in the East German team. Canada''s medal hopeful finishes a disappointing 7th. CHALLENGE: The media contact you to do an interview on the rumours. Do you take the interview and risk having to acknowledge the rumours swirling around the Olympic Village?', 'Speed', 500, 105, 105),

(11, 'Figure Skating', 'Brian Orser vs Brian Boitano controversy and technical scoring', 'The ongoing rivalry between American Brian Boitano and Canadian Brian Orser. Brian Orser won the silver medal at the 1984 Winter Olympics. Brian Boitano placed fifth. Orser placed second at the 1985 World Figure Skating Championships, with Boitano one step below him. Boitano won the next year. When Orser won the 1987 Worlds, held in Cincinnati, Boitano knew he would have to make a change in his skating if he were to beat Orser at the Calgary Olympics on Orser''s home turf of Canada. Boitano was ahead after the compulsory figures, but Orser won the short program. At that time, figures counted for 30% of the score and the short program counted for 20%. The difference between Orser and Boitano was so small that the skater who won the long program would win the title. Orser won 4 judges'' votes outright while Boitano won 3, two remaining judges that placed them with equal total mark gave Boitano higher technical mark, which was the tiebreaker. CHALLENGE: As the Chef de Mission, you are called to field an interview about the technicalities of this win. Do you take the call in this high-stakes American-Canadian rivalry or pass?', 'Strength', 500, 115, 115);